apiVersion: v1
kind: Namespace
metadata:
  name: prod-minecraft
  
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: itzg
  namespace: infra-flux
spec:
  url: https://itzg.github.io/minecraft-server-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: infra-flux
spec:
  releaseName: minecraft
  chart:
    spec:
      chart: minecraft
      version: "4.26.4"
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: infra-flux
  interval: 30m
  values:
    minecraftServer:
      eula: "true"
      version: "1.21.8"
      motd: "elijahs.space"
      serviceType: LoadBalancer
      difficulty: normal
      whitelist: "elijahsspace"
      ops: "elijahsspace"
    persistence:
      enabled: true
      size: 5Gi